### ISSUE TITLE
Connecting to ELK via serial 

### ISSUE THREAD

**Issue by amphipri0n** [cjcharles0/SmartThings#1]
Received the Wemos D1 R2 configured for serial connection.  Setup of the Wemos was easy, however stuck at making the serial connection.  Can you provide instructions on how to physically connect the Wemos to the panel?

**Comment by cjcharles0** [comment]
You should be able to connect to the serial port of your Elk Panel (RS232 or Serial). You should connect the RX of Wemos to TX of Elk, and vice versa. You will then also need to connect Ground of Wemos to Ground of the serial port. If you send me a picture of your panel then I can draw the connection points on that image (ideally one of the overall setup and one of the actual Serial port).

It might be easiest to discuss this through the SmartThings forum for now, if you comment on the main thread with these images then I can respond there.

I suggest not using the RS485 connection since it runs at a different voltage and you would need a small RS485 module to convert between A/B and RX/TX.

**Comment by amphipri0n** [comment]
posted on the Smartthings forum [https://community.smartthings.com/t/paid-request-intergration-with-elk-m1-security-panel/110876/171](url)

**Comment by cjcharles0** [comment]
Im going to close this now as I have updated the instructions and added some new pictures to show the converter needed. Can discuss on the SmartThings forum for further info as it is more accessible for other users there.
