### ISSUE TITLE
Source doesn't compile

### ISSUE THREAD

**Issue by oscar-b** [cjcharles0/SmartThings#2]
Hey!

Trying to compile the Arduino code, but keep running into issues.

First up is line 331 being commented, leading to a compile error:

```ESP-PowerMaxESP8266.ino: In member function 'void MyPowerMax::updatePIN()':
ESP-PowerMaxESP8266:417:17: error: 'Powerlink_PIN_Code' was not declared in this scope
                 Powerlink_PIN_Code = longPIN;
                 ^
ESP-PowerMaxESP8266:422:17: error: 'Powerlink_PIN_Code' was not declared in this scope
```

After uncommenting line 331, it errors on:

```ESP-PowerMaxESP8266.ino: In function 'void handleArmHomeInstant()':
ESP-PowerMaxESP8266:910:20: error: 'Pmax_ARMHOME_INSTANT' was not declared in this scope
     pm.sendCommand(Pmax_ARMHOME_INSTANT);
                    ^
exit status 1
'Pmax_ALARM' was not declared in this scope
```

After disabling that, I'm getting:
```
'Pmax_ARMHOME_INSTANT' was not declared in this scope
```

It continues on, is there any newer code you haven't committed?

**Comment by cjcharles0** [comment]
Yes I dont think I have committed the Pmax library changes yet as I couldnt do it through my normal process. Will see if I can do it manually at some point soon, though for now may be easier to use the firmware bin file as that has all compilation settings added.

**Comment by oscar-b** [comment]
@cjcharles0 thanks, I flashed using the binary instead, was under the impression I needed to make config changes in the source before uploading. 

I’m having problems getting it to enroll to my Powermaster 10 though, it goes into “Downloading” state on the panel (I see basic info but no zone info), but it seems to crash (stops responding to ping). There are two things I suspect:
1. My Powermaster is to old? It’s v15, and the reseller seems to mean the Powerlink module requires v17. There are no options to enroll powerlink in the menus, however it does detect and start doing stuff when it’s connected. 
2. My zone names contain Swedish characters such as åäö, could that cause the code to crash? (Haven’t has time to examine it myself yet). 

Is it possible to get debug log whilst it’s connected to the alarm?

This is the info I'm getting.

```
{"stat":0,
"stat_str":"Disarmed",
"lastCom":0,
"panelType":7,
"panelTypeStr":"PowerMaster10",
"panelModelType":18,
"alarmState":0,
"alarmStateStr":"None",
"alarmTrippedZones":[],
"flags":6,
"flags_ready":false,
"flags_alertInMemory":true,
"flags_trouble":true,
"flags_bypasOn":false,
"flags_last10sec":false,
"flags_zoneEvent":false,
"flags_armDisarmEvent":false,
"flags_alarmEvent":false,
"enroled_zones":[]}
```

**Comment by cjcharles0** [comment]
The newest firmware means no modifications needed in the code, it can all be done through the settings page. Can I suggest we discuss on the SmartThings forum as there is already somebody there who is trying to get things working. Will be more productive together! (side question - TX1 on the Wemos is the most reliable debug connection through a USB-serial dongle which costs 1USD or so)
To answer your questions:
1) Powermaster is already a newish alarm panel compared to many Powermax models, so even though Powerlink might not be officially supported, it should still work. Its just a case of ensuring all the right messages are understood and responded to - for Powermaster most of these messages are not understood, unlike Powermax (though thankfully Powermaster still sends most of these legacy messages to Powerlink).
2) Ive worked with and tested on a few systems which have non-standard characters so that shouldnt be a problem. Its more likely the enrol process which overflows something in Wemos causing a crash, hence me trying to get it working without needing to actively enrol.

https://community.smartthings.com/t/release-visonic-powermax-alarm/84119
