### ISSUE TITLE
MQTT Settings gone after reboot of device

### ISSUE THREAD

**Issue by exetico** [cjcharles0/SmartThings#3]
Hi, 

After i've saved my settings on the `/advanced` page, the device are showing the proper values, if i return to the same page, just after.

However, after a reboot, the settings is gone again.

And also, it's not connecting to my MQTT broker.

I've defined my MQTT IP in `Smart Home Controller IP` - and filled out `MQTT Username` and `MQTT Password:`, too.

Am i doing something wrong, here?

**Comment by exetico** [comment]
_And, while having your attention - if that's OK.. Have you tried to connect it to small ESP device like https://www.aliexpress.com/item/32651747570.html-) Currently i've just a standard ESP Wemos D1 R2 connected to it. However, the network-connection is a bit unstable, and i would like to try it, with another board._

**Comment by exetico** [comment]
_Oh wow... I managed to only enter the IP, and not the port..._

But, it's still not saving the values, after a reboot. So the settings are gone, after a power-cycle. That's not ideal.

I'm also seeing connection dropouts, for some reason. I've one of the small WeMos Mini's and a NodeMCU laying around, but i'm not sure, if i can just use one of them, or if i need a specific firmware for it, a level shifter, or something else.

**Comment by endor-force** [comment]
@exetico Just double check that the power levels on the board matches the same as on Wemos D1 R2 and the alarm, and you should be able to compile the code to those boards (you can not use the precompiled bin file and flash on to these boards, you need to compile it yourself).

I have had some problems when running the arduino code to some board but it seems like it was the board settings, especially IwIP variant to High bandwidth on my Wemos D1 R1.

In your case i would suggest to flash the D1R2 with settings to erase all flash contents and start over, i do not recognize the behaviour from my setup.

![image](https://user-images.githubusercontent.com/1937941/80223407-88da5a00-8648-11ea-815e-f1079f308c15.png)
This is how it looks in arduino gui, i'm sure there is a similar setting when flashing the .bin with esptool.

**Comment by exetico** [comment]
Thanks for the answer, endor-force :-) 

I'm on the HA-integration now, which i totally missed, while trying to get the MQTT-edition of this to work. More details [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-component/55949/1031).

Also, I'm not sure what fixed my problems, but with the other solution ([this](https://github.com/davesmeghead/visonic)), I've not seen a single dropout - so that's great!

_I'll close my issue. I forgot all about it._

**Comment by cjcharles0** [comment]
Hi @endor-force - I have merged the updates you submitted (though not through the Github pull since some of the changes you made were needed because you need to update the PMax library. This will be a BREAKING change for other people using MQTT (since alarm changes will no longer be detected if looking for the 'alarm' status, hence I have not publicised this on SmartThings for the time being.

I have also uploaded a version compiled with ESP Core 2.3 since that version has much better compatibility with HASS and MQTT libraries. Its a bit old and sub optimal, but after lots of testing by several people this was the most reliable fix for ensuring a permanent connection to an MQTT server.

**Comment by endor-force** [comment]
@cjcharles0 The PR was not really related to this issue :)
I am now running the latest version you published and if mqtt server is restarted the alarm loses connection instead of reconnecting.
Not sure if any of the other changes could have impacted this?

Even soft reset will not make the mqtt reconnect again which is strange.

However, just going to the settings,  /advanced and just submitting will connect the mqtt again.
I guess we need to look in to the statement which checks for connectivity and trigger reconnection..
