### ISSUE TITLE
Neohub interface to SmartThings hub V3 - latest SmartThings app

### ISSUE THREAD

**Issue by PaulSitton** [cjcharles0/SmartThings#6]
Hi Charles, I purchased a chip and working fine on V2 and classic SmartThings moved to V3 hub and new app, re-installed to new location set up, the NeoStat bridge is in devices but scan does not pick up the Thermostats and not offered as a brand.... does the interface not work For the new app? Thanks Paul

**Comment by cjcharles0** [comment]
Unfortunately Samsung have not given developers any documentation about how to make things work with the new application, and anything custom currently is unsupported in the new app. That said, the issue is purely in display of custom buttons and information, other things work in the background, so if they follow a Smartthings existing integration then you get some useful features.

This means you can install the old 'Classic' app, configure the device and create the child thermostats, then you can move to the new app and get most functionality out of the device/integration with all the syncing happening in the background..

**Comment by cjcharles0** [comment]
If you have changed to a different Neohub, there is a chance it is running new firmware, hence you may also need to update the firmware running on the NodeMCU. If you go to the NodeMCU webpage then you can upload the latest firmware from Github, but not needed unless you have a brand new Neohub (or a re-branded Neohub from somebody other than Heatmised)

**Comment by PaulSitton** [comment]
Thanks Chris -same neohub tried to do just that in classic - it won’t let me create thermostats so no joy....


On 25 Apr 2020, at 15:37, Chris Charles <notifications@github.com> wrote:

﻿

Unfortunately Samsung have not given developers any documentation about how to make things work with the new application, and anything custom currently is unsupported in the new app. That said, the issue is purely in display of custom buttons and information, other things work in the background, so if they follow a Smartthings existing integration then you get some useful features.

This means you can install the old 'Classic' app, configure the device and create the child thermostats, then you can move to the new app and get most functionality out of the device/integration with all the syncing happening in the background..

**Comment by cjcharles0** [comment]
@PaulSitton Can I ask you to move this to the SmartThings forum please as it is more useful for more users there. It definitely should work fine, but will need to see the errors that are generated from Live Logging in the IDE in order to troubleshoot further.
